project:
  type: website
  output-dir: docs

format:
  revealjs:
    slide-number: true
    footer: <https://topepo.github.io/2024-posit>
    include-before-body: header.html
    include-after-body: footer-annotations.html
    theme: [default, tidymodels.scss]
    width: 1280
    height: 720

knitr:
  opts_chunk:
    echo: true
    collapse: true
    comment: "#>"
    fig.path: "figures/"

fig-format: svg


html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
  
  